---
stages:
- name: Deploy flow to development
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: SA_INSTANCE
    value: ${SA_INSTANCE_NAME}
    type: text
  - name: MH_INSTANCE
    value: ${MH_INSTANCE_NAME}
    type: text
  - name: COS_INSTANCE
    value: ${COS_INSTANCE_NAME}
    type: text
  - name: APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: PIPELINE_API_KEY
    value: ${API_KEY}
    type: text
  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    script: |
      #!/bin/bash
      chmod u+x ./.bluemix/scripts/deploy.sh
      ./.bluemix/scripts/deploy.sh
    docker_image: avigad/java-python
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish