---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: target
    script: |-
      #!/bin/bash
      [[ -d "${ARCHIVE_DIR}" ]] || mkdir ${ARCHIVE_DIR}
      cp .bluemix/scripts/* ${ARCHIVE_DIR}
- name: Deploy flow to development
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    script: |
      #!/bin/bash
      chmod u+x deploy.sh
      ./deploy.sh
    docker_image: avigad/java-python-alpine
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish