---
stages:
- name: Deploy flow to development
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
    - name: SA_INSTANCE
      value: ${SA_INSTANCE_NAME}
      type: text
    - name: MH_INSTANCE
      value: ${MH_INSTANCE_NAME}
      type: text
    - name: COS_INSTANCE
      value: ${COS_INSTANCE_NAME}
      type: text
    - name: APP_NAME
      value: ${CF_APP_NAME}
      type: text
    - name: PIPELINE_API_KEY
      value: ${API_KEY}
      type: text
  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    script: |
      #!/bin/bash
      pip3 install -r requirements.txt
      python3 ./src/data_historian.py
    docker_image: avigad/java-python-alpine
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish

  properties:

  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${APP_NAME}
    script: |
      #!/bin/bash 
      chmod u+x deploy.sh
      ./deploy.sh
    docker_image: avigad/java-python-alpine 
  hooks:
   - enabled: true
    label: null
    ssl_enabled: false 
    url: http://lms-api/v1/messaging/webhook/publish
