---
stages:
- name: Deploy flow to development
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    script: |
      #!/bin/bash
      chmod u+x deploy.sh
      ./deploy.sh
    docker_image: avigad/java-python-alpine
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish